- README.md
- src/core/genlite.class.ts
- src/core/helpers/genlite-confirmation.class.ts
- src/core/plugins/genlite-settings.plugin.ts
- src/index.ts
- src/plugins/genlite-camera.plugin.ts
- src/plugins/genlite-drop-recorder.plugin.ts
- src/plugins/genlite-item-highlight.plugin.ts
- src/plugins/genlite-npc-highlight.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
- src/plugins/genlite-wiki-data-collection.plugin.ts
- userscript-banner.txt
* Added a settings plugin
* Changed plugin order
* Features that submit data to my server to assist with the wiki now warn you about your IP address being part of the requests
> GenLite settings plugin

- src/plugins/genlite-locations.plugin.ts
- Removed the button for opening map in popup (May re-add in different spot)
- Compass on hover and on click to map
- Fixes for dungeons, fae, world stairs
- Some more location data added (Still not 100% accurate)
> More Locations/Map Plugin Features and Fixes

- src/core/genlite.class.ts
- src/core/globals.ts
- src/core/plugins/genlite-settings.plugin.ts
- src/index.ts
- src/plugins/genlite-drop-recorder.plugin.ts
- src/plugins/genlite-hit-recorder.plugin.ts
- src/plugins/genlite-menu-scaler.plugin.ts
- src/plugins/genlite-npc-highlight.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
- src/plugins/genlite-xp-calculator.plugin.ts
Big Features
- Total EXP calculator tooltip added by hovering over total levels
- Can reset a xp calc by shift clicking a skill (including total levels)
- Can reset all calcs by ctrl-shift clicking any skill
- Right Menu scaler just for samual
- Added a dps tracker complete with UI
- can reset the cumDps by shift clicking overlay
- several bugfixes
> I'm Alive (The one with alot of UI work)

- README.md
- src/plugins/genlite-hit-recorder.plugin.ts
- src/plugins/genlite-xp-calculator.plugin.ts
- userscript-banner.txt
Bug fixes, also better way to calculate the average action xp
> Bug fixes for xp-calc and hit recorder

- README.md
- src/plugins/genlite-locations.plugin.ts
- userscript-banner.txt
Styling needs to be cleaned up and better determine how to add/remove custom css to the UI; Most issues seem to be when using custom classes and the styles being removed on login? This might not fix the issue if styles are being removed when the users logs in and out
Do NOT merge until @dpeGit and myself test further (Putting in PR for when/if we find no issues)
> Possible fix for banner issue

- package-lock.json
- src/core/genlite-plugin-loader.class.ts
- src/core/genlite.class.ts
- src/core/helpers/genlite-confirmation.class.ts
- src/core/plugins/genlite-settings.plugin.ts
- src/index.ts
- src/plugins/genlite-drop-recorder.plugin.ts
- src/plugins/genlite-hit-recorder.plugin.ts
- src/plugins/genlite-menu-scaler.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
- src/plugins/genlite-wiki-data-collection.plugin.ts
- src/plugins/genlite-xp-calculator.plugin.ts
Added calculator for baseXP as calculated by 2Pi
Added Total counter to HitRecorder
Cleaned up and typescriptified some code
BugFixes for drop recorder and other things
> BaseXP, HitRecorder Additions, Code Cleanup, and as always Bug Fixes

- README.md
- src/core/genlite.class.ts
- src/core/globals.ts
- src/core/plugins/genlite-commands.plugin.ts
- src/core/plugins/genlite-settings.plugin.ts
- src/index.ts
- src/plugins/genlite-camera.plugin.ts
- src/plugins/genlite-drop-recorder.plugin.ts
- src/plugins/genlite-generalchatcommand.plugin.ts
- src/plugins/genlite-hit-recorder.plugin.ts
- src/plugins/genlite-item-highlight.plugin.ts
- src/plugins/genlite-item-tooltips.plugin.ts
- src/plugins/genlite-menu-scaler.plugin.ts
- src/plugins/genlite-menuswapper.plugin.ts
- src/plugins/genlite-npc-highlight.plugin.ts
- src/plugins/genlite-npcmenuswapper.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
- src/plugins/genlite-sound-notification.plugin.ts
- src/plugins/genlite-wiki-data-collection.plugin.ts
- userscript-banner.txt
Detailing all changes made in the last few commits
- Genlite Settings now has a filter box to help find settings. Can search by setting name or by plugin name
- Genlite Commands now prints a help prompt on login
- General Chat Commands
-- //logged - prints time logged in
-- //played - prints time played (stored locally only since this implemented)
- Item Tool Tips
-- Now Takes in to account conditional food. Pacifist and Wanders are TODO
-- added shop value tooltip
- menu swapper
-- option for stairs to be on shift click or right click. Disabled by default
- NPC Highlight
-- Name Tag is now centered above enemy health bar in combat
- Sound Notification
-- Added option for sound effect on low health. Disabled by default
- Wiki Data Collection
-- automatic scan now spreads out npcs over 20 …
> alot of changes read description

- README.md
- src/core/genlite.class.ts
- src/core/globals.ts
- src/plugins/genlite-hit-recorder.plugin.ts
- src/plugins/genlite-item-highlight.plugin.ts
- src/plugins/genlite-locations.plugin.ts
- src/plugins/genlite-npc-highlight.plugin.ts
- src/plugins/genlite-sound-notification.plugin.ts
- userscript-banner.txt
- HitRecorder
-- Added more nerd shit functions
- ItemHighlights
--Added the ability to hide tags while still using the filter
- Locations
-- Fixed settings so they work properly
- SoundNotifcations
-- Added the ability to override game volume
-- Added a low inventory alert
> More Nerd Shit, More Settings, More Annoying Sounds

- src/plugins/genlite-camera.plugin.ts
slider to change render distance, terrain, buildings, etc
> add render distance setting

- README.md
- src/plugins/genlite-menuswapper.plugin.ts
- userscript-banner.txt
these were accidentally controlled by the hide stairs toggle in settings.
skipping version 1.25 to override another fork
> patch left click bank/trade

- README.md
- src/core/genlite.class.ts
- src/core/plugins/genlite-commands.plugin.ts
- src/core/plugins/genlite-settings.plugin.ts
- src/index.ts
- src/plugins/genlite-camera.plugin.ts
- src/plugins/genlite-chat.plugin.ts
- src/plugins/genlite-drop-recorder.plugin.ts
- src/plugins/genlite-generalchatcommand.plugin.ts
- src/plugins/genlite-highscores.plugin.ts
- src/plugins/genlite-hit-recorder.plugin.ts
- src/plugins/genlite-inventory.plugin.ts
- src/plugins/genlite-item-highlight.plugin.ts
- src/plugins/genlite-locations.plugin.ts
- src/plugins/genlite-music.plugin.ts
- src/plugins/genlite-npc-highlight.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
- src/plugins/genlite-sound-notification.plugin.ts
- src/plugins/genlite-wiki-data-collection.plugin.ts
- src/plugins/genlite-xp-calculator.plugin.ts
- userscript-banner.txt
mostly bug fixes, and hopefully the final version of wikidatacollection
> I havent been able to keep track of all the changes

- .github/workflows/main-workflow-manual.yaml
- .github/workflows/main-workflow.yaml
- README.md
- package-lock.json
- package.json
- src/plugins/genlite-recipe-recorder.plugin.ts
fixed auto version bumping but it will involve commits bloating, not sure if this is the path we want to go down
> auto version bumping

- src/index.ts
- src/plugins/genlite-camera.plugin.ts
Removed Hide Roof setting in GenLite since it is in Genfanad officially now
Added Client Hook-ins
> Client v0.120 Hook Ins and Initial Updates

- .github/workflows/main-workflow-manual.yaml
- .github/workflows/main-workflow.yaml
- README.md
- package-lock.json
- package.json
- src/plugins/genlite-item-highlight.plugin.ts
- webpack.config.js
> Reenabled Item Priorities

- README.md
- package.json
- src/plugins/genlite-itemdisplay.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
Moved itemdisplay stuff to a function,
recipe recorder mats are now sorted so order of selection doesn't matter
> Dan is a picky asshole

- src/index.ts
Helps browsers find the script and list it in their sources tab, giving access to view the code and set breakpoints.
> Added to scriptText replacement string, so browser's can find the script.

- README.md
- package-lock.json
- package.json
- src/core/item-data.ts
- src/index.ts
- src/plugins/genlite-fps.plugin.ts
- src/plugins/genlite-hit-recorder.plugin.ts
- src/plugins/genlite-wiki-data-collection.plugin.ts
- thirdPartyModules/Stats.js/LICENSE
- thirdPartyModules/Stats.js/build/stats.module.js
- thirdPartyModules/Stats.js/src/Stats.js
Added an FPSCounter using a (modified) Stats.js
Moved dps element to a better location
Hit Recorder now ignore the first hit on login because overkill issues
> FPSCounter and small changes

- README.md
- package.json
- src/index.ts
- src/plugins/genlite-camera.plugin.ts
- src/plugins/genlite-menuswapper.plugin.ts
- src/plugins/genlite-quest.plugin.ts
- adds a quest counter to player info ui
- option to de-prioritize attack options to right click only
> quest plugin and right-click attack

- README.md
- package.json
- src/core/genlite.class.ts
- src/core/interfaces/plugin.interface.ts
- src/core/plugins/genlite-ui-plugin.ts
- src/plugins/genlite-enhanced-context-menu.plugin.ts
- src/plugins/genlite-generalchatcommand.plugin.ts
- src/plugins/genlite-inventory.plugin.ts
1. Added Hooks for Enhanced Context Menu
2. Lookup Objects now properly respects object distances
3. Removed Unnecessary Console Logs
4. Added Pretty Sliders (mainly a targeted fix Firefox)
5. Slider Value Labels now properly call State Handler when modified
6. Added Inventory Anti Shift Drag to the UI
> Initial Bug Fixes targeting GenLite UI

- src/core/plugins/genlite-ui-plugin.ts
- src/index.ts
- src/plugins/genlite-camera.plugin.ts
- src/plugins/genlite-chat.plugin.ts
- src/plugins/genlite-item-highlight.plugin.ts
- src/plugins/genlite-locations.plugin.ts
- src/plugins/genlite-npc-highlight.plugin.ts
- src/plugins/genlite-playertools.plugin.ts
- src/plugins/genlite-resize.plugin.ts
- new plugin to enable/disable UI transitions
- remove april fools
- location label font to match the rest of the game
- chat and camera plugins' handlePluginState implemented
> UI transition + small changes

- README.md
- package.json
- src/core/interfaces/plugin.class.ts
- src/plugins/genlite-enhanced-context-menu.plugin.ts
> fix enhanced context plugin

- README.md
- package.json
- src/index.ts
- src/plugins/genlite-music.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
music
- prev/next/shuffle buttons
- currently playing display
recipe recorder
- display inputs/outputs and percentages
- search bar
> UI tabs for Music and Recipe Recorder

- src/plugins/genlite-recipe-recorder.plugin.ts
> fix chrome css

- src/core/genlite.class.ts
- src/core/plugins/genlite-ui-plugin.ts
- src/index.ts
- src/plugins/genlite-drop-recorder.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
- src/plugins/genlite-tagging.plugin.ts
- tag plugin: add tags to players in friends list
- drops plugin: add ui tab
- ui plugin: make camera view resizing an option (default true)
- recipe recorder: lock chat when searching, style update
> tag plugin, drops ui, and small changes

- src/core/interfaces/chat.interface.ts
- src/core/plugins/genlite-database.plugin.ts
- src/plugins/genlite-chat.plugin.ts
- chat plugin can count to 3 in all scenarios
- recolor PMs:
-- color for new messages
-- color for replied-to
-- color for sent
- preserve chat actually works between logins
> chat improvements

- README.md
- package.json
- src/index.ts
- src/plugins/genlite-chat.plugin.ts
- display per-player chats in genlite ui
- not implemented:
-- search by player name
-- sending via genlite ui (maybe)
> sidebar for private messages

- package-lock.json
- src/plugins/genlite-locations.plugin.ts
Some know issues still is location label setting required for coordinates to show up; however given sneakpeak of locations coming soon may change the header to be more customizable outside the scope of locations (As the vanilla client will soon possible have locations above minimap)
Still need more semicolons; will go through the code and add them or look for a linting process to auto add them before pushing
> Switched to new Settings Menu UI

- src/index.ts
- src/plugins/genlite-simplified-chat-ui.plugin.ts
[Example UI result](https://i.imgur.com/PJCZyB1.png)
> Simplified chat UI

- README.md
- package.json
- src/core/plugins/genlite-database.plugin.ts
- src/core/plugins/genlite-ui-plugin.ts
- src/plugins/genlite-camera.plugin.ts
- src/plugins/genlite-chat.plugin.ts
- src/plugins/genlite-drop-recorder.plugin.ts
- src/plugins/genlite-enhanced-context-menu.plugin.ts
- src/plugins/genlite-recipe-recorder.plugin.ts
Chat sidebar, private, public, pictures, etc.
bug fixes
delete buttons for recipe and drop recorders
sort button for drop recorder
bank and trading window fix
> chat + more
